version: '3.0'
services:
  coffeeshop:
    image: coffeeshop_app:latest
    ports:
      - "8080:8080"
    env_file:
      - config.env
    volumes:
      - go-modules:/go/pkg/mod

volumes:
  go-modules: