@host = http://localhost:3000
@keycloak_host = http://localhost:8080

###

GET {{host}}/send-email

###

###
# @name campaigns
POST {{host}}/campaigns
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
	"name": "Ismael ezequiel alves",
	"content": "some long content",
	"emails": ["salmeidabatista@gmail.com", "ismaelv3kell@gmail.com"]
}

###

@campaign_id = {{campaigns.response.body.id}}

###
// GET /campaigns
GET {{host}}/campaigns
Authorization: Bearer {{access_token}}

###
// GET /campaigns/{campaign_id}
GET {{host}}/campaigns/{{campaign_id}}
Authorization: Bearer {{access_token}}

###
// GET /ping
GET {{host}}/ping

###
// PATCH /campaigns/delete
PATCH {{host}}/campaigns/delete/{{campaign_id}}
Authorization: Bearer {{access_token}}

###
// PATCH /campaigns/start
PATCH {{host}}/campaigns/start/{{campaign_id}}
Authorization: Bearer {{access_token}}

###
# @name token
POST {{keycloak_host}}/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailn&username=ismael@edusynch.team&password=123456&grant_type=password

###
@access_token = {{token.response.body.access_token}}